# Generated by Django 4.2.6 on 2023-10-08 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='content_creator/profile/images')),
                ('about', models.TextField(max_length=1000)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.country')),
                ('studio', models.ManyToManyField(to='super_admin.studio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('overview', models.TextField(max_length=500)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='content_creator/movies/images')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('part_no', models.PositiveSmallIntegerField()),
                ('plot', models.TextField(max_length=500)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(upload_to='content_creator/movies_part/images')),
                ('video', models.FileField(upload_to='content_creator/movies_part/videos')),
                ('content_rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='super_admin.contentrating')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.country')),
                ('genre', models.ManyToManyField(to='super_admin.genre')),
                ('language', models.ManyToManyField(to='super_admin.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.PositiveSmallIntegerField()),
                ('overview', models.TextField(blank=True, max_length=500)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='content_creator/season/images')),
                ('is_enable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('language', models.ManyToManyField(to='super_admin.language')),
            ],
        ),
        migrations.CreateModel(
            name='ShowPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='content_creator/show_person/profile/images')),
                ('is_enable', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.country')),
            ],
        ),
        migrations.CreateModel(
            name='ShowPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.showrole')),
                ('show_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.showperson')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('overview', models.TextField(max_length=500)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='content_creator/series/images')),
                ('country', models.ManyToManyField(to='super_admin.country')),
                ('genre', models.ManyToManyField(to='super_admin.genre')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.series'),
        ),
        migrations.AddField(
            model_name='season',
            name='studio',
            field=models.ManyToManyField(to='super_admin.studio'),
        ),
        migrations.CreateModel(
            name='MovieTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('movie_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.moviepart')),
            ],
        ),
        migrations.AddField(
            model_name='moviepart',
            name='person',
            field=models.ManyToManyField(to='content_creator.showpersonrole'),
        ),
        migrations.AddField(
            model_name='moviepart',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.studio'),
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('episode_no', models.PositiveSmallIntegerField()),
                ('plot', models.TextField(max_length=500)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(upload_to='content_creator/episode/images')),
                ('video', models.FileField(upload_to='content_creator/episode/videos')),
                ('content_rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='super_admin.contentrating')),
                ('person', models.ManyToManyField(to='content_creator.showpersonrole')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.season')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.contentcreator')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.series')),
            ],
        ),
        migrations.CreateModel(
            name='ContentMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.contentcreator')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.moviepart')),
            ],
        ),
    ]
