# Generated by Django 4.2.6 on 2023-10-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_creator.movie'),
        ),
        migrations.AlterField(
            model_name='season',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
