# Generated by Django 4.2.6 on 2023-10-08 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='subscriber/profile/images')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_subscription', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin.subscriptionplan')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriber.subscriber')),
            ],
        ),
    ]
